//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AromasEstoque
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetail
    {
        public int DetailId { get; set; }
        public int SaleId { get; set; }
        public string ProductName { get; set; }
        public int Amount { get; set; }
        public decimal SalePrice { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
