//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AromasEstoque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int TransactionId { get; set; }
        public Nullable<byte> EmployeeId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public System.DateTime EventDate { get; set; }
        public string Currency { get; set; }
        public decimal Amount { get; set; }
        public byte Parcel { get; set; }
        public string Category { get; set; }
        public string Comment { get; set; }
        public Nullable<int> JobId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
