//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AromasEstoque
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultBalance
    {
        public int BalanceId { get; set; }
        public System.DateTime ReferenceDate { get; set; }
        public decimal Balance { get; set; }
        public string AdjustmentType { get; set; }
        public Nullable<byte> EmployeeId { get; set; }
    }
}
